import { Booking } from "@/types";

export const sampleBookings: Booking[] = [
  {
    id: "booking-1",
    userId: "user-1",
    carId: "1",
    carName: "BMW M3 Competition",
    carModel: "2024 BMW M3 Competition",
    carImage: "/images/hero/car1.png",
    status: "upcoming",
    pickupDate: "2024-12-20",
    returnDate: "2024-12-22",
    pickupLocation: "Downtown Location",
    returnLocation: "Downtown Location",
    pickupTime: "10:00",
    returnTime: "10:00",
    rentalDays: 2,
    dailyRate: 350,
    totalAmount: 700,
    paymentStatus: "paid",
    bookingDate: "2024-12-15",
    notes: "Please ensure the car is clean and ready for pickup",
    driverAge: "30-39",
    additionalDriver: false,
    insurance: "basic"
  },
  {
    id: "booking-2",
    userId: "user-1",
    carId: "2",
    carName: "Mercedes-AMG GT",
    carModel: "2024 Mercedes-AMG GT",
    carImage: "/images/hero/car2.png",
    status: "active",
    pickupDate: "2024-12-10",
    returnDate: "2024-12-12",
    pickupLocation: "Airport Location",
    returnLocation: "Airport Location",
    pickupTime: "14:00",
    returnTime: "14:00",
    rentalDays: 2,
    dailyRate: 450,
    totalAmount: 900,
    paymentStatus: "paid",
    bookingDate: "2024-12-05",
    notes: "Business trip - need GPS navigation",
    driverAge: "25-29",
    additionalDriver: true,
    insurance: "premium"
  },
  {
    id: "booking-3",
    userId: "user-1",
    carId: "3",
    carName: "Audi RS6 Avant",
    carModel: "2024 Audi RS6 Avant",
    carImage: "/images/hero/car3.png",
    status: "completed",
    pickupDate: "2024-11-25",
    returnDate: "2024-11-28",
    pickupLocation: "City Center",
    returnLocation: "City Center",
    pickupTime: "09:00",
    returnTime: "17:00",
    rentalDays: 3,
    dailyRate: 400,
    totalAmount: 1200,
    paymentStatus: "paid",
    bookingDate: "2024-11-20",
    notes: "Family vacation - need child seat",
    driverAge: "40-49",
    additionalDriver: false,
    insurance: "basic"
  },
  {
    id: "booking-4",
    userId: "user-1",
    carId: "4",
    carName: "Porsche 911 Turbo S",
    carModel: "2024 Porsche 911 Turbo S",
    carImage: "/images/hero/car5.png",
    status: "cancelled",
    pickupDate: "2024-11-15",
    returnDate: "2024-11-17",
    pickupLocation: "Downtown Location",
    returnLocation: "Downtown Location",
    pickupTime: "11:00",
    returnTime: "11:00",
    rentalDays: 2,
    dailyRate: 550,
    totalAmount: 1100,
    paymentStatus: "refunded",
    bookingDate: "2024-11-10",
    notes: "Cancelled due to weather conditions",
    driverAge: "30-39",
    additionalDriver: false,
    insurance: "premium"
  },
  {
    id: "booking-5",
    userId: "user-1",
    carId: "5",
    carName: "Tesla Model S Plaid",
    carModel: "2024 Tesla Model S Plaid",
    carImage: "/images/hero/car1.png",
    status: "upcoming",
    pickupDate: "2024-12-25",
    returnDate: "2024-12-30",
    pickupLocation: "Airport Location",
    returnLocation: "Airport Location",
    pickupTime: "08:00",
    returnTime: "20:00",
    rentalDays: 5,
    dailyRate: 380,
    totalAmount: 1900,
    paymentStatus: "paid",
    bookingDate: "2024-12-18",
    notes: "Holiday trip - need charging station access",
    driverAge: "25-29",
    additionalDriver: true,
    insurance: "basic"
  },
  {
    id: "booking-6",
    userId: "user-1",
    carId: "6",
    carName: "Lamborghini Huracán EVO",
    carModel: "2024 Lamborghini Huracán EVO",
    carImage: "/images/hero/car2.png",
    status: "completed",
    pickupDate: "2024-10-20",
    returnDate: "2024-10-21",
    pickupLocation: "Luxury Location",
    returnLocation: "Luxury Location",
    pickupTime: "12:00",
    returnTime: "12:00",
    rentalDays: 1,
    dailyRate: 800,
    totalAmount: 800,
    paymentStatus: "paid",
    bookingDate: "2024-10-15",
    notes: "Special occasion - birthday celebration",
    driverAge: "30-39",
    additionalDriver: false,
    insurance: "premium"
  },
  {
    id: "booking-7",
    userId: "user-1",
    carId: "7",
    carName: "Ferrari 488 GTB",
    carModel: "2024 Ferrari 488 GTB",
    carImage: "/images/hero/car1.png",
    status: "upcoming",
    pickupDate: "2024-12-30",
    returnDate: "2025-01-02",
    pickupLocation: "Monaco Location",
    returnLocation: "Monaco Location",
    pickupTime: "15:00",
    returnTime: "15:00",
    rentalDays: 3,
    dailyRate: 900,
    totalAmount: 2700,
    paymentStatus: "pending",
    bookingDate: "2024-12-20",
    notes: "New Year celebration - luxury experience",
    driverAge: "40-49",
    additionalDriver: false,
    insurance: "premium"
  },
  {
    id: "booking-8",
    userId: "user-1",
    carId: "8",
    carName: "McLaren 720S",
    carModel: "2024 McLaren 720S",
    carImage: "/images/hero/car2.png",
    status: "completed",
    pickupDate: "2024-09-10",
    returnDate: "2024-09-12",
    pickupLocation: "Track Location",
    returnLocation: "Track Location",
    pickupTime: "09:00",
    returnTime: "18:00",
    rentalDays: 2,
    dailyRate: 850,
    totalAmount: 1700,
    paymentStatus: "paid",
    bookingDate: "2024-09-05",
    notes: "Track day experience - professional driver training",
    driverAge: "25-29",
    additionalDriver: true,
    insurance: "premium"
  }
];
